version: 2
updates:
  - package-ecosystem: bun
    directory: "/"
    schedule:
      interval: weekly
    groups:
      all-minor-patch:
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      all-actions:
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
